#=========================== Spring Config ===========================#
spring:
  profiles: test
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/focre?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ffk_jiaoyi
    type: com.alibaba.druid.pool.DruidDataSource
    filters: wall,mergeStat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000

#=========================== Focre Config ===========================#
focre:
  server:
    port:
      rest: 8280
      adminRest: 8281
  randomKey: randomKey
  desKey: focretes
  expiration: 0
  secret: devMovillage
  tsDiffer: 180
  # Open Swagger UI docs
  enable-swagger: true

logging:
  level.root: info
  level.com.focre: info
  path: logs/