#=========================== Spring Config ===========================#
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/focre?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ffk_jiaoyi
    type: com.alibaba.druid.pool.DruidDataSource
    filters: wall,mergeStat,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    password: ffk_jiaoyi
    database: 15

#=========================== Focre Config ===========================#
focre:
  server:
    port:
      rest: 8080
      adminRest: 8081
  randomKey: randomKey
  desKey: focredev
  expiration: 0
  secret: devMovillage
  tsDiffer: 180
  # Open Swagger UI docs
  enable-swagger: true

logging:
  level:
    com:
      alibaba:
        druid: info
      focre: info
    org:
      apache:
        dubbo: warn
      springframework: info
    root: info
  path: logs/
